controller_manager:
  ros__parameters:
    update_rate: 100  #Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    leg_velocity_controller:
      type: velocity_controller/JointGroupVelocityController

leg_velocity_controller:
  ros__parameters:
    joints:
      - fr_leg_joint
      - ml_leg_joint
      - rr_leg_joint